package entities;
// Generated Nov 24, 2013 1:07:37 PM by Hibernate Tools 3.6.0

import DAL.RewardDAL;
import org.codehaus.jettison.json.JSONObject;




/**
 * Point generated by hbm2java
 */
public class Point  implements java.io.Serializable, JSONable {


     private Integer id;
     private Reward reward;
     private String currency;

    public Point() {
    }

    public Point(Reward reward, String currency) {
       this.reward = reward;
       this.currency = currency;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reward getReward() {
        return this.reward;
    }
    
    public void setReward(Reward reward) {
        this.reward = reward;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Override
    public void fromJSON(JSONObject obj) {
        try {
            if (obj.has("currency")) {
                this.setCurrency(obj.getString("currency"));
            }
            if (obj.has("id")) {
                this.setId(obj.getInt("id"));
            }
            if (obj.has("reward")) {
                this.setReward(RewardDAL.getRewardById(obj.getInt("reward")));
            }
        } catch (Exception ex) {
            System.out.println("Error in Point-fromJson: " + ex.getMessage());
        }
    }

    @Override
    public JSONObject toJSON() {
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", this.getId());
            obj.put("currency", this.getCurrency());
            if(this.reward != null){
                obj.put("name", this.reward.getName());
                obj.put("description", this.reward.getDescriptiom());
            }
        } catch (Exception ex) {
            System.out.println("Error Point-toJSON: " + ex.getMessage());
        }
        return obj;
    }




}


