package entities;
// Generated Nov 24, 2013 1:07:37 PM by Hibernate Tools 3.6.0


import DAL.RewardDAL;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.codehaus.jettison.json.JSONObject;

/**
 * Quest generated by hbm2java
 */
public class Quest  implements java.io.Serializable, JSONable {


     private Integer id;
     private Reward reward;
     private int maxLevel;
     private Date validityDateFrom;
     private Date validityDateTo;

    public Quest() {
    }

	
    public Quest(Reward reward, int maxLevel) {
        this.reward = reward;
        this.maxLevel = maxLevel;
    }
    public Quest(Reward reward, int maxLevel, Date validityDateFrom, Date validityDateTo) {
       this.reward = reward;
       this.maxLevel = maxLevel;
       this.validityDateFrom = validityDateFrom;
       this.validityDateTo = validityDateTo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reward getReward() {
        return this.reward;
    }
    
    public void setReward(Reward reward) {
        this.reward = reward;
    }
    public int getMaxLevel() {
        return this.maxLevel;
    }
    
    public void setMaxLevel(int maxLevel) {
        this.maxLevel = maxLevel;
    }
    public Date getValidityDateFrom() {
        return this.validityDateFrom;
    }
    
    public void setValidityDateFrom(Date validityDateFrom) {
        this.validityDateFrom = validityDateFrom;
    }
    public Date getValidityDateTo() {
        return this.validityDateTo;
    }
    
    public void setValidityDateTo(Date validityDateTo) {
        this.validityDateTo = validityDateTo;
    }

     @Override
    public JSONObject toJSON() {
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", this.getId());
            obj.put("maxLevel", this.getMaxLevel());
            obj.put("validityDateFrom", this.getValidityDateFrom());
            obj.put("validityDateTo", this.getValidityDateTo());
            if(this.reward != null){
                obj.put("name", this.reward.getName());
                obj.put("description", this.reward.getDescriptiom());
            }
        } catch (Exception ex) {
            System.out.println("Error Quest-toJSON: " + ex.getMessage());
        }
        return obj;
    }

    @Override
    public void fromJSON(JSONObject obj) {
        try {
            if (obj.has("maxLevel")) {
                this.setMaxLevel(obj.getInt("maxLevel"));
            }
            if (obj.has("validityDateFrom")) {
                String dateString = obj.getString("validityDateFrom");
                if (dateString != null && !dateString.isEmpty()) {
                    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                    this.setValidityDateFrom(format.parse(dateString));
                }
            }
            if (obj.has("validityDateTo")) {
                String dateString = obj.getString("validityDateTo");
                if (dateString != null && !dateString.isEmpty()) {
                    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                    this.setValidityDateTo(format.parse(dateString));
                }
            }
            if (obj.has("id")) {
                this.setId(obj.getInt("id"));
            }
            if (obj.has("reward")) {
                this.setReward(RewardDAL.getRewardById(obj.getInt("reward")));
            }
        } catch (Exception ex) {
            System.out.println("Error in Quest-fromJson: " + ex.getMessage());
        }
    }




}


