package entities;
// Generated Nov 24, 2013 1:07:37 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import org.codehaus.jettison.json.JSONObject;

/**
 * TeamRole generated by hbm2java
 */
public class TeamRole  implements java.io.Serializable, JSONable {


     private Integer id;
     private String name;
     private Set<TeamPlayer> teamPlayers = new HashSet<TeamPlayer>(0);

    public TeamRole() {
    }

	
    public TeamRole(String name) {
        this.name = name;
    }
    public TeamRole(String name, Set<TeamPlayer> teamPlayers) {
       this.name = name;
       this.teamPlayers = teamPlayers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<TeamPlayer> getTeamPlayers() {
        return this.teamPlayers;
    }
    
    public void setTeamPlayers(Set<TeamPlayer> teamPlayers) {
        this.teamPlayers = teamPlayers;
    }

     @Override
    public JSONObject toJSON() {
        try {
             JSONObject obj = new JSONObject();
             obj.put("id", this.id);
             obj.put("name", this.name);
             return obj;
         } catch (Exception ex) {
             
         }
         return null;
    }

    @Override
    public void fromJSON(JSONObject obj) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


