package entities;
// Generated Nov 4, 2013 10:45:52 PM by Hibernate Tools 3.6.0



/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private Integer id;
     private EventType eventType;
     private Application application;
     private ObjectType objectType;
     private Reward reward;

    public Action() {
    }

    public Action(EventType eventType, Application application, ObjectType objectType, Reward reward) {
       this.eventType = eventType;
       this.application = application;
       this.objectType = objectType;
       this.reward = reward;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EventType getEventType() {
        return this.eventType;
    }
    
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public ObjectType getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(ObjectType objectType) {
        this.objectType = objectType;
    }
    public Reward getReward() {
        return this.reward;
    }
    
    public void setReward(Reward reward) {
        this.reward = reward;
    }




}


