package entities;
// Generated Nov 4, 2013 10:45:52 PM by Hibernate Tools 3.6.0

import DAL.RewardDAL;
import org.codehaus.jettison.json.JSONObject;

/**
 * Badge generated by hbm2java
 */
public class Badge implements java.io.Serializable, JSONable {

    private Integer id;
    private Reward reward;
    private String icon;

    public Badge() {
    }

    public Badge(Reward reward, String icon) {
        this.reward = reward;
        this.icon = icon;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Reward getReward() {
        return this.reward;
    }

    public void setReward(Reward reward) {
        this.reward = reward;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Override
    public JSONObject toJSON() {
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", this.getId());
            obj.put("icon", this.getIcon());
            if(this.reward != null){
                obj.put("name", this.reward.getName());
                obj.put("description", this.reward.getDescriptiom());
            }
        } catch (Exception ex) {
            System.out.println("Error Badge-toJSON: " + ex.getMessage());
        }
        return obj;
    }

    @Override
    public void fromJSON(JSONObject obj) {
        try {
            if (obj.has("icon")) {
                this.setIcon(obj.getString("icon"));
            }
            if (obj.has("id")) {
                this.setId(obj.getInt("id"));
            }
            if (obj.has("reward")) {
                this.setReward(RewardDAL.getRewardById(obj.getInt("reward")));
            }
        } catch (Exception ex) {
            System.out.println("Error in Badge-fromJson: " + ex.getMessage());
        }
    }

}
