package entities;
// Generated Nov 4, 2013 10:45:52 PM by Hibernate Tools 3.6.0


import DAL.ApplicationDAL;
import DAL.RewardDAL;
import java.util.HashSet;
import java.util.Set;
import org.codehaus.jettison.json.JSONObject;

/**
 * ObjectType generated by hbm2java
 */
public class ObjectType  implements java.io.Serializable, JSONable {


     private Integer id;
     private Application application;
     private String name;
     private String description;
     private Set<Object> objects = new HashSet<Object>(0);
     private Set<Action> actions = new HashSet<Action>(0);

    public ObjectType() {
    }

	
    public ObjectType(Application application, String name) {
        this.application = application;
        this.name = name;
    }
    public ObjectType(Application application, String name, String description, Set<Object> objects, Set<Action> actions) {
       this.application = application;
       this.name = name;
       this.description = description;
       this.objects = objects;
       this.actions = actions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Application getApplication() {
        return this.application;
    }
    
    public void setApplication(Application application) {
        this.application = application;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Object> getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set<Object> objects) {
        this.objects = objects;
    }
    public Set<Action> getActions() {
        return this.actions;
    }
    
    public void setActions(Set<Action> actions) {
        this.actions = actions;
    }

    @Override
    public JSONObject toJSON() {
        JSONObject obj = new JSONObject();
        try {
            obj.put("id", this.getId());
            obj.put("name", this.getName());
            obj.put("description", this.getDescription());
            if(this.application != null){
                obj.put("application", this.application.getId());
            }
        } catch (Exception ex) {
            System.out.println("Error ObjectType-toJSON: " + ex.getMessage());
        }
        return obj;
    }

    @Override
    public void fromJSON(JSONObject obj) {
        try {
            if (obj.has("name")) {
                this.setName(obj.getString("name"));
            }
            if (obj.has("description")) {
                this.setName(obj.getString("description"));
            }
            if (obj.has("id")) {
                this.setId(obj.getInt("id"));
            }
            if (obj.has("application")) {
                this.setApplication(ApplicationDAL.getApplicationById(obj.getInt("application")));
            }
        } catch (Exception ex) {
            System.out.println("Error in ObjectType-fromJson: " + ex.getMessage());
        }
    }



}


