package entities;
// Generated Nov 4, 2013 10:45:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TeamRole generated by hbm2java
 */
public class TeamRole  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<TeamPlayer> teamPlayers = new HashSet<TeamPlayer>(0);

    public TeamRole() {
    }

	
    public TeamRole(String name) {
        this.name = name;
    }
    public TeamRole(String name, Set<TeamPlayer> teamPlayers) {
       this.name = name;
       this.teamPlayers = teamPlayers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<TeamPlayer> getTeamPlayers() {
        return this.teamPlayers;
    }
    
    public void setTeamPlayers(Set<TeamPlayer> teamPlayers) {
        this.teamPlayers = teamPlayers;
    }




}


